### ISSUE TITLE
Spectrum peak intensity / specsaturation not correct

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/NOVACProgram#108]
It appears that the 'specsaturation' parameter is not being correctly calculated in the EvaluationLogs. In the attached example, it seems to be set to a constant 0.11 which is clearly wrong. The fitsaturation variable as it should be, but it's also higher which shows that a specsaturation of 0.11 is much too low. This bug then also leads to the 'Spectrum peak intensity' being displayed incorrectly in the scan view of the NOVAC program (see attached screenshot).

[D2J2827_191218_2301_0.txt](https://github.com/NOVACProject/NOVACProgram/files/3989847/D2J2827_191218_2301_0.txt)

[D2J2827_191218_2301_0.pak.zip](https://github.com/NOVACProject/NOVACProgram/files/3989853/D2J2827_191218_2301_0.pak.zip)

![2019-12-18_16-02-38](https://user-images.githubusercontent.com/15023271/71285248-9473e800-2319-11ea-89a3-ba006abce598.png)

**Comment by dnorgaard-usgs** [comment]
Seems this is already fixed in latest code. 

Using code compiled yesterday (3.2 snapshot):
[D2J2827_200201_2236_0.txt](https://github.com/NOVACProject/NOVACProgram/files/4155165/D2J2827_200201_2236_0.txt)

Using code compiled last June (3.1):
[D2J2827_200202_0015_0.txt](https://github.com/NOVACProject/NOVACProgram/files/4155168/D2J2827_200202_0015_0.txt)
