### ISSUE TITLE
Download all pak-files 

### ISSUE THREAD

**Issue by mattias42** [NOVACProject/NOVACProgram#2]
There is a bug in the program when running on 64-bit OS or on Windows 7 (unclear reason) that the program only downloads all existing pak-files at startup. If there is a upload.pak existing in the device then the program doesn't continue downloading data. Reason is unclear and needs to be investigated. 
The program does seem to work as expected on Windows XP (32bit).

**Comment by dnorgaard-usgs** [comment]
The problem appeared to be that the software was failing to reconcile the upload.pak file size on a 64-bit Windows OS with that of what was expected from reading the directory contents on the electronics box (Linux).  It is unclear exactly what the differences is, but a work around was placed by Mattias to ignore the download of and file size check of upload.pak. All other u*.pak files are downloaded w/o file size check.

The downside of this work around is that the first file ever created (upload.pak) after a restart of the electronics box is never downloaded.  It was decided that this was an acceptable loss in order to address the bigger issue.
