### ISSUE TITLE
Evaluation region is missing from eval-logs

### ISSUE THREAD

**Issue by mattias42** [NOVACProject/NOVACProgram#4]

**Comment by dnorgaard-usgs** [comment]
On Thu, Jan 25, 2018 at 1:50 AM, Santiago Arellano wrote:
Hi,

The issue had to do with the problem we have encountered sometimes to judge results produced by other users, without knowing exactly the parameters used for the evaluation.

For real-time operation the information is included in the configuration.xml file, and it looks for example like this:
"<spectrometer>
        <serialNumber>D2J2818</serialNumber>
        <model>S2000</model>
        <channel number="0">
                <Reference>
                        <name>SO2</name>
                        <path>C:\NOVAC\scanDOAS_Etna\D2J2818\D2J2818_SO2_293K_Bogumil_HP500_Master.txt</path>
                        <shift>fix to 3.20</shift>
                        <squeeze>fix to 1.00</squeeze>
                </Reference>
                <Reference>
                        <name>O3</name>
                        <path>C:\NOVAC\scanDOAS_Etna\D2J2818\D2J2818_O3_223K_Voigt_HP500_Master.txt</path>
                        <shift>link to 0</shift>
                        <squeeze>link to 1</squeeze>
                </Reference>
                <Reference>
                        <name>RING</name>
                        <path>C:\NOVAC\scanDOAS_Etna\D2J2818\D2J2818_Ring_HR_HP500_Master.txt</path>
                        <shift>link to 0</shift>
                        <squeeze>link to 1</squeeze>
                </Reference>
                <fitLow>386</fitLow>
                <fitHigh>576</fitHigh>
        </channel>
</spectrometer>"

A suggestion would be to include the same information in the individual scan files:"'/Scans/Serial_Date_Time_Channel.txt" and in the "EvaluationLog_Serial_Date.txt" file (which is a collection of all individual scan files produced in the day). Of course, the format of the information above could be changed to adapt the existing one.

The same information should then be included in the PostEvaluationLog file generated when the user runs re-evaluation. In this case it is probably even more important because I think presently there is no 'configuration.xml' file generated for post-evaluations, so there is no way to retrieve the information behind the results.

Best regards,
Santiago.
